# Generated by Django 4.2.7 on 2023-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='автор')),
                ('body', models.CharField(blank=True, max_length=255, null=True, verbose_name='цитата')),
            ],
        ),
    ]
